name: Create Release

on:
  push:
    paths:
    - '.version' # Trigger only when .version is modified
    branches:
    - main # Or your main branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Read version
      id: read_version
      run: |
        VERSION=$(cat .version)
        echo "version=$VERSION" >> $GITHUB_ENV

    - name: Create Git tag
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git tag -a "v$VERSION" -m "Release v$VERSION"
        git push origin "v$VERSION"

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v$VERSION"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
